$base            = 0xff161b17
$surface         = 0xff1e251f
$overlay         = 0xff2a332b
$muted           = 0xff5a6b5f
$subtle          = 0xff869e8e
$text            = 0xffdce5df
$love            = 0xff5e3d3d
$gold            = 0xffe0af4d
$rose            = 0xffa3ad8d
$pine            = 0xff4e8b71
$foam            = 0xff94b8a3
$iris            = 0xff9ba670
$highlightLow    = 0xff232d25
$highlightMed    = 0xff394a3e
$highlightHigh   = 0xff4e6454
